[package]
name = "axum-tungstenite"
version = "0.3.0"
categories = ["asynchronous", "network-programming", "web-programming"]
description = "WebSocket connections for axum directly using tungstenite"
edition = "2021"
homepage = "https://github.com/davidpdrsn/axum-tungstenite"
keywords = ["http", "web", "framework"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/davidpdrsn/axum-tungstenite"

[dependencies]
async-trait = "0.1.89"
axum-core = "0.5.6"
base64 = "0.22.1"
bytes = "1.11.1"
futures-util = { version = "0.3.32", default-features = false, features = ["alloc"] }
http = "1.4.2"
http-body = "1.0.1"
hyper = "1.10.1"
hyper-util = { version = "0.1.20", features = ["tokio"] }
sha-1 = "0.10.1"
tokio = { version = "1.52.3", features = ["rt"] }
tokio-tungstenite = "0.29.0"

[dev-dependencies]
axum = "0.8.9"
